# Resumen {.unnumbered}

El Programa estatal de vigilancia entomológica y control integral de enfermedades trasmitidas por vector realiza diversas actividades para la prevención de enfermedades, las cuales se guían con actividades de vigilancia que proporcionan índices de riesgo entomológico. Por ello, se creó un paquete de R para calcular los índices de riesgo entomológico de forma automática y oportuna para la toma de decisiones. Todas las actividades se capturan diariamente en una plataforma, donde es posible descargar los datos para su reporte y análisis. En el caso de Vigilancia por Ovitrampa (VO), la plataforma calcula los índices de riesgo, pero para la actividad de Estudio Entomológico (EE) los calcula por manzana trabajada, estos índices se requieren por localidad de riesgo de manera semanal.

El análisis de riesgo entomológico se hace en hojas de cálculo, por lo que el manejo de la información es ineficiente, la estructura de la base de datos es compleja y adaptar consultas con pequeñas modificaciones es impráctico, además la visualización georreferenciada de esta plataforma es pobre e inestable.

Se requiere calcular índices de riesgo del EE por tipo de estudio, localidad de riesgo y por semana epidemiológica de manera automatizada. La actividad de EE evalúa una muestra antes (encuesta) y después (verificación) de las actividades de control integral para determinar el riesgo entomológico que hay en un área grande a trabajar (Sectores o Localidad) y si requiere reforzar acciones de control y prevención.

El paquete de R desarrollado permitirá el análisis oportuno y automático de los datos provenientes de la actividad de vigilancia entomológica. Utilizando herramientas de Ciencia de Datos, este paquete se utiliza la base de datos de la plataforma “Vigilancia Entomológica y Control Integral del Vector” del Instituto Nacional de Salud Pública, en colaboración con la Secretaría de Salud y el Centro Nacional de Prevención y Control de Enfermedades (CENAPRECE). Con el fin de calcular y analizar los índices de riesgo entomológico, y con esto gestionar información para la toma de decisiones en la prevención de enfermedades transmitidas por vector.