---
title: "Obtencion de  los datos"
---

# Obtencion de  los datos

El Programa estatal de vigilancia entomología y control integral de enfermedades
trasmitidas por vector, realiza diversas actividades para la prevención de 
enfermedades (Control Larvario (CL) , Rociado a caso (RaC), Rociado intra 
domiciliario(RI) y Nebulización espacial (N)) las cuales se guían con 
actividades de vigilancia (Vigilancia entomológica con ovitrampas, (VO) )las 
cuales proporcionan índices de riesgo entomológico(EE), Estudios entomológicos 
en fase larval y pupal, y Estudios entomovirológicos (EEV)) 

Todas las actividades mencionadas se capturan diariamente en una plataforma, 
donde es posible descargar los datos para su reporte y análisis. Para la 
actividad de EE los calcula por manzana trabajada, estos índices se requieren 
por localidad de riesgo de manera semanal. 

La actividad de EE evalúa una muestra antes(encuesta) y después(verificación) 
de las actividades de control integral para determinar el riesgo entomológico 
que hay en un área grande a trabajar (Sectores o Localidad) y si requiere 
reforzar las acciones de control


## Descripcion de la base de datos

Vigilancia entomológica, al monitoreo de presencia y abundancia de los insectos
vectores de alguna enfermedad en un lugar determinado.
